### ISSUE TITLE
xunit vs multiprocess

### ISSUE THREAD

**Issue by jpellerin** [nose-devs/nose#2]
<b>What steps will reproduce the problem?</b>
1. Run xunit unit test w/ --processes=2
2. See fails

<b>What is the expected output? What do you see instead?</b>

All of nose's tests should pass under --processes=2

<b>Please use labels and text to provide additional information.</b>

Problem is, xunit creates a file and writes to it when it sees reportable events. For that to work 
under mp, all the reporting has to happen in the main process. That will require a major redesign of 
how mp worker processes report their results to the main process.

Google Code Info:
Issue #: 267
Author: jpelle...@gmail.com
Created On: 2009-05-16T13:04:45.000Z
Closed On:

**Comment by nichochar** [comment]
Thanks Ignas, that's really helpful.

**Comment by crusaderky** [comment]
Any plan about fixing this problem in the main nose distribution?

**Comment by jszakmeister** [comment]
@crusaderky If you'd like to see this fixed, I suggest putting together a PR to fix it.  It's not likely to climb up the list otherwise.

I'd also suggest taking a look at Nose 2.  It's really the future of Nose, and it has both JUnit XML support and MP support.

**Comment by kahunacohen** [comment]
nose2 hasn't gained much traction. I've stuck with nose1 after trying out
2. nose2 isn't quite there yet and nobody's really picked it up. No
disrespect, just the truth. There's a nose1 plugin that can deal with this
issue more or less.

**Comment by jszakmeister** [comment]
> nose2 hasn't gained much traction.

It won't unless more people use it, and more importantly, help oout.

> I've stuck with nose1 after trying out
> 2. nose2 isn't quite there yet and nobody's really picked it up. No
> disrespect, just the truth. There's a nose1 plugin that can deal with this
> issue more or less.

None taken.  OTOH, Nose will go away at some point.  It's pretty crufty as it stands, and fixing some issues would require breaking plugins.  Others, such as the multiprocessing brokeness, can only be fixed with some significant effort and likely a number of architecture changes--and I apologize, but it's more time than I can commit to.

So at the end of the day, Nose only grows harder to maintain with time--and quite frankly, with all the stuff I've got going on right now, I'm seriously considering dropping out of the open source scene for a while.

Nose 2 is really where the attention needs to be.

**Comment by kahunacohen** [comment]
I agree that it's up to users to move nose forward, but at the same time if
nose2 were really that needed it would be getting done. This says to me
that either everyone's leaving nose for other things, or nose 1 suffices
enough for most people that they don't see value in nose2, or a combination
of the two. I'd say the latter. A lot of people are moving on to other
things, and those who continue to use nose1 (I do for many cases) think
it's good enough for most situations. The only real issue I've ever had
with nose1, was this mp issue, which I've generally been able to work
around. We're all busy and generally concentrate on what we need to do to
get our jobs done. We contribute to open-source only when we feel the
benefit of contributing outweighs the cost. The fact that nose1 may be full
of cruft only becomes a problem when it really interferes with our work.
Apparently that's not the case for most people (yet).

**Comment by p00j4** [comment]
any idea if its fixed or does it work in nose2 now? or --with-xunit & --processes are still not compatible for any of nose version?

However, @jpellerin : thanks for the great help 👍  xunitmp comes as rescue

**Comment by therewillbeblood** [comment]
i use nose 1.3.7 inside a virtualenv where install junit_xml==1.6 and nose_xunitmp==0.4.0 and then i can successfully run:
`python ${venv_home}/bin/nosetests -vv --processes=8 --process-timeout=21600 --exe --with-xunitmp --xunitmp-file "${xml_file}" ${files_to_check}`

The process timeout is necessary because the default value is ridiculously low
